### ISSUE TITLE
Awesome app!

### ISSUE THREAD

**Issue by Rai** [nparsons08/android-messages#2]
First of all, good job! Been looking for something like this! I'm having some issues getting it to work though. 

I'm using Windows 10, and the QR code pops open in chrome and i use my phone to scan it. Then, the chrome tab just loads messages.google.com, instead of the app. The app remains white the whole time.

**Comment by jszuslik** [comment]
I get the same issue on mac

**Comment by astrotars** [comment]
I think it is an issue with the URL. I'll release a new build shortly. Just dealing with a few issues with my computer at the moment :)

**Comment by astrotars** [comment]
Updated in [releases](https://github.com/nparsons08/android-messages/releases/tag/v1.0.1)! Enjoy!
