### ISSUE TITLE
Can only interact by dragging

### ISSUE THREAD

**Issue by chinook9** [nparsons08/android-messages#4]
After downloading the latest release on linux mint 19.2, the only thing that happens when clicking on the window is dragging. it looks like this is caused by  electron.css:
`body {
  -webkit-app-region: drag;
}`
Forcing the whole page to be draggable.

**Comment by astrotars** [comment]
@chinook9 this is definitely a known issue. I don't have control over the parent window as google is serving it up. Any thoughts on a way around it? Feel free to submit a PR. :)

**Comment by chinook9** [comment]
Closing since my pull request was merged. Thanks!
